name: "PHPUnit Tests"

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    phpunit:
        name: "PHPUnit Tests"

        runs-on: ${{ matrix.operating-system }}

        services:
            database:
                image: 'postgres:13-alpine'
                env:
                    POSTGRES_PASSWORD: main
                    POSTGRES_USER: main
                    POSTGRES_DB: main
                ports:
                    # Maps tcp port 5432 on service container to the host
                    - 5432:5432
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        strategy:
            matrix:
                php-version:
                    - "8.0"
                operating-system:
                    - "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    php-version: "${{ matrix.php-version }}"
                    ini-values: memory_limit=-1

            -   name: "Cache dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-${{ matrix.php-version }}"
                    restore-keys: "php-${{ matrix.php-version }}"

            -   name: "Install dependencies"
                run: "composer install --no-interaction --no-progress --no-suggest"

            -   name: "phpunit"
                run: vendor/bin/phpunit --coverage-clover coverage.xml

            -   name: "Publish to coveralls"
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    composer global require php-coveralls/php-coveralls
                    php-coveralls --json_path=coveralls-upload.json --coverage_clover=coverage.xml -v
